### ISSUE TITLE
feat(unocss): unocss-preset-primitives plugin for styling Kobalte Elements 🎉

### ISSUE THREAD

**Issue by zirbest** [fabien-ml/kobalte#27]
A Unocss plugin for styling Kobalte Elements 🎉
[unocss-preset-primitives](https://github.com/zirbest/unocss-preset-primitives#kobalte)

**Comment by fabien-ml** [comment]
Awesome, I will add it to the styling section of the doc.
Thanks.

**Comment by fabien-ml** [comment]
Done (https://kobalte.dev/docs/overview/styling#usage-with-unocss)
