### ISSUE TITLE
feat(css-selector): use the same css selector approche used in radix-ui and headless-ui

### ISSUE THREAD

**Issue by zirbest** [fabien-ml/kobalte#34]
Can i make  a PR([@kobalte/tailwindcss](https://github.com/fabien-ml/kobalte/blob/main/packages/tailwindcss))  to use the same API used in [headless-ui](https://headlessui.com/react/menu#using-data-attributes) and [radix-ui](https://www.radix-ui.com/docs/primitives/overview/styling#styling-a-state) ?

change `attribute selector` **from:**
``` html
<div data-checked>...</div>
```
```css
.item[data-checked] { ... }
```

**to:**

``` html
<div data="checked">...</div>
```
```css
.item[data='checked'] { ... }
```

**Comment by jesseb34r** [comment]
Isn't this totally different in that `data-checked` is a native html attribute whereas `data="checked"` is a custom attribute? I assume this is an intentional choice to do it this way.

**Comment by fabien-ml** [comment]
`data=` is not a valid HTML data-attribute. radix use `data-state=` which is valid, but hold only a single value. Headless UI put all the values in the same `data-headlessui-state` attribute but it will require to rewrite how the attributes are set in all components.

**Comment by zirbest** [comment]
It's lot of refactoring :100: 
```
data-state='hover checked'
```
I will close this issue :+1:
