### ISSUE TITLE
Request: Text input fields

### ISSUE THREAD

**Issue by milesj** [fabien-ml/kobalte#38]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Right now kobalte offers checkboxes, radios, and selects, but does not have a basic text input field (and textarea also).

It would be great if kobalte supported this, as it's nice to standardize on the same APIs (like `validationState`, label handling, error messages, etc).

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by fabien-ml** [comment]
Hi, its on the roadmap https://kobalte.canny.io/feature-requests. I'm planning to work on it when i'm done with the datepicker

**Comment by fabien-ml** [comment]
Update: since it's not that complexe I will works on it now and release within the week (+ some perf improvement).

**Comment by milesj** [comment]
@fabien-ml Sounds great.

Also, that canny link isn't  anywhere on the repo. I'd suggest adding it to the readme or something. Wasn't aware it existed.

**Comment by fabien-ml** [comment]
Available in v`0.2.0`.

**Comment by milesj** [comment]
@fabien-ml Thanks for the super fast turn around 🙏
