### ISSUE TITLE
`Checkbox` inside `Popover` triggers `focus-visible` on click

### ISSUE THREAD

**Issue by tienpv222** [fabien-ml/kobalte#39]
**Describe the bug**
When inside `Popover`, toggling a `Checkbox` with mouse activates `data-focus-visble`.

**Reproduce**
https://stackblitz.com/edit/node-rpxsaq

**Comment by fabien-ml** [comment]
Hi thanks for the bug report. 

I think it's the same bug as in `solid-aria` (https://github.com/solidjs-community/solid-aria/issues/60) since both are the same port of `react-aria`. 

However I didn't found a solution for this yet. 😖

**Comment by fabien-ml** [comment]
Looks like it's an unsolved problem in react-aria too (https://github.com/adobe/react-spectrum/issues/2380).
