### ISSUE TITLE
`Select.Trigger` cannot focus back using keyboard

### ISSUE THREAD

**Issue by tienpv222** [fabien-ml/kobalte#57]
**To Reproduce**
https://stackblitz.com/edit/node-z2nn98?file=src%2Fmain.tsx

In the demo, there are 2 tabs containing a `TextField` and a `Select`. The one with `TextField` can tab back to `Tabs.List`, while the other cannot.

**Additional context**
There are two other issues that I'm not sure how they are related, so I'll list them here just in case.

1. Using `Select` in dev mode complains `Computations created outside a 'createRoot' or 'render' will never be disposed`. This can be seen in the demo above too.

1. `Select.Item` not showing `data-hover` on hover. The image below is from the docs site.

    ![chrome_KMHJisZiRN](https://user-images.githubusercontent.com/31667324/213361237-62a1755e-101c-4a0e-819e-9d2ddff62383.png)

**Comment by fabien-ml** [comment]
Hi, thanks for the report. It looks like it's not just in `Tabs`. i'm digging into the problem

**Comment by fabien-ml** [comment]
fixed in `v0.4.0`.

**Comment by tienpv222** [comment]
> fixed in `v0.4.0`.

That was super fast, thank you a lot.
