### ISSUE TITLE
Improve performance of Popover

### ISSUE THREAD

**Issue by jcmonnin** [fabien-ml/kobalte#72]
When having a lot of popovers on a page, the creation of the popovers can take a non-negligible time.

Example:
https://stackblitz.com/edit/solidjs-templates-4wy9yr?file=src/Tag.tsx
(click on the + or - to see the time it takes generate the page)

While this use case might look a bit exotic, it's sometimes useful to allow to show more details on request on a lot of elements with a popover.

It's desirable to do as little work as possible on the creation of the popover. Following workaround swaps a button for a Popover in the click handler (it's probably not correct from an accessibility point of view):
```
function MyTag3(props: MyTagProps) {
  const [open, setOpen] = createSignal(false);

  return (
    <Show
      when={!open()}
      fallback={
        <Popover.Root isOpen={open()} onOpenChange={setOpen}>
          <Popover.Trigger class={styles.popover__trigger}>
            {props.name}
          </Popover.Trigger>
          <Popover.Portal>
            <Popover.Content class={styles.popover__content}>
              <Popover.Arrow />
              {props.value}
            </Popover.Content>
          </Popover.Portal>
        </Popover.Root>
      }
    >
      <button class={styles.tag} onClick={() => setOpen(true)}>
        {props.name}
      </button>
    </Show>
  );
}
```

The request is to investigate if it's possible delay some of the work done for the construction of a popover until is pressed, in order to improve the overhead to create a popover on a page.

**Comment by fabien-ml** [comment]
improved in `v0.6.0`.
