### ISSUE TITLE
Expose pointer coordinates on press events

### ISSUE THREAD

**Issue by ceopaludetto** [fabien-ml/kobalte#77]
**Is your feature request related to a problem? Please describe.**
I wanna implement a ripple effect in button component but I can't access pointer coordinates in press events

**Describe the solution you'd like**
Expose clientX and clientY(when applicable) in press events

**Describe alternatives you've considered**
I've been using native events with refs

**Additional context**

**Comment by fabien-ml** [comment]
`onPress` has been removed in `v0.6.0`, you can use "normal" `onClick` handlers.
