### ISSUE TITLE
Add ui-vertical and ui-horizontal in tailwind plugin

### ISSUE THREAD

**Issue by ceopaludetto** [fabien-ml/kobalte#80]
**Is your feature request related to a problem? Please describe.**
I wanna create a divider using tailwind

**Describe the solution you'd like**
Add ui-horizontal and ui-vertical in tailwind plugin

**Describe alternatives you've considered**
Manually add theses variants in my tailwind configuration

**Additional context**

**Comment by fabien-ml** [comment]
added in `v0.6.0`.
