### ISSUE TITLE
Add group and peer variants to tailwind plugin

### ISSUE THREAD

**Issue by ceopaludetto** [fabien-ml/kobalte#81]
**Is your feature request related to a problem? Please describe.**
I wanna style based on group and peer states

**Describe the solution you'd like**
Add group and peer variants in tailwind plugin

**Describe alternatives you've considered**
Manually add theses variants in my tailwind configuration

**Additional context**

**Comment by ceopaludetto** [comment]
Just for curiosity:

```js
const variants = [
  "focus",
  "hover",
  "disabled",
  "invalid",
].map((variant) => [
  [`${prefix}-${variant}`, `[data-${variant}]`],
  [`${prefix}-not-${variant}`, `:not([data-${variant}])`],
]).flat();

matchVariant(
  "group",
  (value, { modifier }) =>
    modifier ? `:merge(.group\\/${e(modifier)})${value} &` : `:merge(.group)${value} &`,
   { values: Object.fromEntries(variants) },
);
```

**Comment by fabien-ml** [comment]
Hi, thanks for reporting the issue, I will add `group` and `peer` variants in the next version.
However there will be some breaking changes in `v0.6.0` related to styling : `hover`, `focus`, `focus-visible` and `active` data-attributes will no longer exist and you will need to use the native css selector or tailwind equivalent.

**Comment by ceopaludetto** [comment]
> Hi, thanks for reporting the issue, I will add `group` and `peer` variants in the next version.
> 
> However there will be some breaking changes in `v0.6.0` related to styling : `hover`, `focus`, `focus-visible` and `active` data-attributes will no longer exist and you will need to use the native css selector or tailwind equivalent.

Yeah, I've followed the discussion in Discord. My package relies on this handlings but I'm comfortable with the changes.

**Comment by fabien-ml** [comment]
added in `v0.6.0`.
